devtype: ToRRouter
peerdevtype: LeafRouter
t0_downlinks:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
t0_uplinks:
  - 28
  - 29

t1_downlinks:
  - 0
  - 1

t1_uplinks:
  - 28
  - 29 

t2_downlinks:
  - 0
  - 1

