stages:
  - test
  - generate

playbook:
  stage: test
  script:
    - ansible-playbook generate_config.yml --tags t1 --diff --check

playbook:
  stage: generate
  script: 
    - ansible-playbook generate_config.yml --tags t1 --diff 
