stages:
  - test
  - generate
  - deploy

validate:
  stage: test
  script:
    - ansible-playbook generate_config.yml --tags t1 --diff --check

minigraph files:
  stage: generate
  script: 
    - ansible-playbook generate_config.yml --tags t1 --diff 

configuration:
  stage: deploy
  script: 
    - ansible-playbook deploy.yml 
