stages:
  - test
  - generate

validate:
  stage: test
  script:
    - ansible-playbook generate_config.yml --tags t1 --diff --check

minigraph file generation:
  stage: generate
  script: 
    - ansible-playbook generate_config.yml --tags t1 --diff 
