stages:
  - test
  - generate
  - deploy

validate:
  stage: test
  script:
    - ansible-playbook generate_config.yml --tags t1 --diff --check

minigraph files:
  stage: generate
  script: 
    - ansible-playbook generate_config.yml --tags t1 --diff 
    - ansible-playbook -i hosts deploy.yml 
