devtype: ToRRouter
peerdevtype: LeafRouter
t0_downlinks:
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
  - 45
  - 46
  - 47
  - 54
  - 55
  - 56
  - 57
  - 58
  - 59
  - 60
  - 61
  - 62
  - 63

lagmembers: 2

t0_uplinks:
  - 0
  - 1
  - 2
  - 3

t1_downlinks:
  - 6
  - 7
  - 8
  - 9

t1_uplinks:
  - 0
  - 1 
  - 2
  - 3

t2_downlinks:
  - 6
  - 7
  - 8
  - 9
